### ISSUE TITLE
ofxFaceRecognizer example project compiling problem

### ISSUE THREAD

**Issue by alana92** [antimodular/ofxFaceRecognizer#2]
I'm running the example project (from the ofxFaceRecognizer addon folder) in the of_v0.9.8_osx_release (downloaded from the of website) in xcode (v. 9.1) with opencv (v. 3.4.0 ) installed on macOS High Sierra and getting the following compiling errors:

Error:

`/Applications/of_v0.9.8_osx_release/addons/ofxOpenCV2461/src/ofxCvImage.h:82:29: Virtual function 'getPixels' has a different return type ('unsigned char *') than the function it overrides (which has return type 'ofPixels_<unsigned char> &')`

From code:

` virtual unsigned char*  getPixels();`

Error:

`/Applications/of_v0.9.8_osx_release/addons/ofxOpenCV2461/src/ofxCvContourFinder.h:58:29: Field type 'ofxCvGrayscaleImage' is an abstract class`

From code:
```
 protected:

    int  _width;
    int  _height;
    ofxCvGrayscaleImage     inputCopy;
    CvMemStorage*           contour_storage;
    CvMemStorage*           storage;
    CvMoments*              myMoments;
    vector<CvSeq*>          cvSeqBlobs;  //these will become blobs
    
    ofPoint  anchor;
    bool  bAnchorIsPct;      

    virtual void reset();
```

Error:

`/Applications/of_v0.9.8_osx_release/addons/ofxOpenCV2461/src/ofxCvHaarFinder.h:51:22: Field type 'ofxCvGrayscaleImage' is an abstract class`

From code:

```
protected:
	CvHaarClassifierCascade* cascade;
	string haarFile;
	ofxCvGrayscaleImage img;
	float scaleHaar;
	unsigned neighbors;
```

Issue also logged on the ofxopencv2461 github repository, see: https://github.com/pkmital/ofxOpenCV2461/issues/1

Issue also logged on the openframeworks github repository, see: https://github.com/openframeworks/openFrameworks/issues/5850

Please advise

**Comment by stephanschulz** [comment]
I'm on OS X 10.12 and this compiles fine for me with of 0.9.8

this: https://www.dropbox.com/s/u9kf7d98mqp21m5/ofxFaceRecognizer.zip?dl=0

**Comment by alana92** [comment]
Thank you so much! This works and is exactly what I was looking for.

**Comment by prismspecs** [comment]
Would you mind re-posting that zip file? I'm running into the same error as alana92 and can't seem to find any solutions

**Comment by antimodular** [comment]
i hope i did not change anything since then
https://www.dropbox.com/s/zo54cqjgfd0u3in/ofxFaceRecognizer.zip?dl=0

also here is a project using a different method; openface.
https://www.dropbox.com/s/853f96k9jry5moe/Comparator.zip?dl=0
